name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install worker-build
        run: cargo install -q worker-build
      - name: Build for Cloudflare Workers
        run: worker-build --release
    # - name: Run tests
    #   run: cargo test --verbose
